# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
 if Vagrant.has_plugin? "vagrant-vbguest"
 config.vbguest.no_install = true
 config.vbguest.auto_update = false
 config.vbguest.no_remote = true
 end
 config.vm.define :clienteUbuntu1 do |clienteUbuntu1|
 clienteUbuntu1.vm.box = "bento/ubuntu-20.04"
 clienteUbuntu1.vm.network :private_network, ip: "192.168.100.4"
 clienteUbuntu1.vm.hostname = "clienteUbuntu1"
 end
end